name: nexonev
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: 6.0.5
  font_awesome_flutter: 10.4.0
  email_validator: 2.1.17
  shared_preferences: 2.1.1
  http: 1.0.0
  animated_custom_dropdown: 1.5.0
  google_sign_in: 6.1.4
  lottie: 2.4.0
  google_fonts: 5.0.0
  smooth_page_indicator: 1.1.0
  awesome_dialog: 2.2.1
  syncfusion_flutter_pdfviewer: 23.1.40 
  share: 2.0.4
  razorpay_flutter: 1.3.5
  fluttertoast:
  flutter_map: 5.0.0
  latlong2: 
  geolocator: 9.0.2
  geocoding: 2.1.0
  socket_io_client: 2.0.2 
  sticky_grouped_list: 3.1.0
  intl: 
  image_picker: 1.0.0
  http_parser: 4.0.2
  jwt_decoder: 2.0.1
  connectivity_plus: 5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/pdf/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
